name: Bash CI

on: [push]
jobs:
 unittest:
  runs-on: ubuntu-latest
  steps:
    - name: get shUnit2
      run: git clone https://github.com/kward/shunit2.git
    
    - name: run test
      run: ./test.sh
